server:
  servlet:
    context-path: /crm
##数据源配置
spring:
  datasource:
    type: com.mchange.v2.c3p0.debug.AfterCloseLoggingComboPooledDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/crm01?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
    ##freemarker
  freemarker:
    content-type: text/html
    charset: utf-8
    template-loader-path: classpath:/views/
    suffix: .ftl

## mybatis配置
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.shsxt.vo;com.shsxt.query;com.shsxt.dto
  configuration:
    map-underscore-to-camel-case: true

##pagehelper
pagehelper:
  helper-dialect: mysql


